# Generated by Django 6.0.2 on 2026-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='cargo_type',
            field=models.CharField(blank=True, choices=[('container', 'Container'), ('bulk', 'Bulk Cargo'), ('liquid', 'Liquid Cargo'), ('general', 'General Cargo'), ('none', 'None')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='last_position_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='last_position_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
